### ISSUE TITLE
[Feat] TMDB Manager 생성

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/alpaka_theater#3]
### 작업 설명 🛠️
- TMDB로부터 데이터를 가져올 Manager를 생성합니다.
- 데이터를 가져오는데에 필요한 기본적인 라이브러리들의 의존성을 추가합니다.

### Todos ✅
- [ ] TMDB APIKey 구조체 생성
- [ ] TMDB Manager 생성
- [ ] 프로젝트에 Alamofire, KingFisher, SnapKit 의존성 추가
