### ISSUE TITLE
[Feat] 홈 화면 만들기

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/alpaka_theater#5]
### 작업 설명 🛠️
- 프로젝트를 생성시 가장 먼저 보일 Home 화면을 생성합니다.
- Home 화면에는 검색바를 이용한 검색 기능과, 검색해서 가져온 영화에 대한 데이터를 collectionView로 보여줍니다.
- collectionView는 상하 방향으로 스크롤되며, 한 행에는 3개의 item이 보여집니다

### Todos ✅
- [x] Home 화면 생성
- [x] searchBar Layout 및 UI 구현
- [x] collectionView Layout 및 UI 구현
- [x] 영화 검색 기능 구현
