### ISSUE TITLE
[Feat] SearchDetail 화면 구현하기

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/alpaka_theater#7]
### 작업 설명 🛠️
- 홈 화면의 검색 결과를 눌렀을떄 나오는 SearchDetail 화면을 구현합니다
- SearchDetail 화면에는 비슷한 영화, 추천 영화, 포스터 이미지 3가지의 정보를 보여줍니다
- 3가지의 정보는 각각 횡스크롤이 가능한 collectionView에 담겨있으며, 이 collectionView를 cell로 하는 tableView를 구현합니다

### Todos ✅
- [ ] SearchDetail 화면 Layout 및 UI 구현
- [ ] TMDB의 similar, recommendation, image API 통신하기
- [ ] 횡스크롤의 collectionView를 cell로 갖는 tableView를 구현하여 데이터 보여주기
